version: '2'
services:
  web:
    build:
        context : .
        dockerfile: app/Dockerfile
        args:
          - host_ip
    environment:
      - PLACE_SEARCH_API_DEBUG=1
    ports:
      - "2225:22"
      - "8080:80"
    volumes:
      - ../../:/var/www/PlaceSearchApi
